### ISSUE TITLE
Access denied for user ''@'172.19.0.3

### ISSUE THREAD

**Issue by devchop2** [devchop2/dev-techHub#2]
```
[Nest] 53  - 10/22/2024, 3:05:03 PM   ERROR [ExceptionHandler] Access denied for user ''@'172.19.0.3' (using password: YES)
server-computer-1  | Error: Access denied for user ''@'172.19.0.3' (using password: YES)
server-computer-1  |     at Packet.asError (/techHub/node_modules/mysql2/lib/packets/packet.js:738:17)
server-computer-1  |     at ClientHandshake.execute (/techHub/node_modules/mysql2/lib/commands/command.js:29:26)
server-computer-1  |     at PoolConnection.handlePacket (/techHub/node_modules/mysql2/lib/connection.js:481:34)
server-computer-1  |     at PacketParser.onPacket (/techHub/node_modules/mysql2/lib/connection.js:97:12)
server-computer-1  |     at PacketParser.executeStart (/techHub/node_modules/mysql2/lib/packet_parser.js:75:16)
server-computer-1  |     at Socket.<anonymous> (/techHub/node_modules/mysql2/lib/connection.js:104:25)
server-computer-1  |     at Socket.emit (node:events:514:28)
server-computer-1  |     at addChunk (node:internal/streams/readable:376:12)
server-computer-1  |     at readableAddChunk (node:internal/streams/readable:349:9)
server-computer-1  |     at Readable.push (node:internal/streams/readable:286:10)
```

below is docker-compose.yaml
```
#computers
services:
  server-computer: #computer name
    build:
      context: . #path
      dockerfile: dockerFile.graphql #file name
    env_file:
      - ./.env
    ports:
      - 3000:3000 #port forwarding
    volumes:
      - ./src:/techHub/src

  db-computer:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DATABASE_DATABASE}
      MYSQL_USER: ${DADTABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 3306:3306

```
